version: 1.2.2

services:
  - cpanel
  - gateway
  - indexer
  - optimizer
  - search
  - logwatcher
  - historic-search
  - grafana

common:
  client.env: "env"
  client.id: "episilia"
  client.license.key: ""
  datastore.s3.accesskey: ""
  datastore.s3.secretkey: ""
  datastore.s3.region: ""
  datastore.s3.endpoint.url: "https://objectstore.e2enetworks.net"
  datastore.s3.bucket: "episilia-bucket"
  datastore.s3.folder: "episilia-folder"
  datastore.s3.work.folder: "work-folder"
  datastore.s3.sign.payload: "true"
  datastore.s3.url.prefix: "s3://"
  datastore.s3.useArn: "false"
  datastore.s3.assumerole: ""
  kafka.indexer.logs.topics: "log"
  kafka.metadata.broker.list: "localhost:9092"
  kafka.indexer.group: "episilia-indexer-group"
  kafka.topic.cpanel.out: "cpaneld"
  ops.cpanel.data.publish.interval.seconds: "600"
  ops.license.url: "episilia_cpanel:8080"
  ops.log.debug: "true"
  kafka.indexer.broker.list: "localhost:9092"
  kafka.indexer.broker.security.mode: "none"    #othervalues as well(login, oauth, kerberos
  kafka.indexer.broker.security.protocol: "SASL_SSL" #plaintext, ssl, sasl_plaintext, sasl_ssl
  kafka.broker.sasl.mechanism: "SCRAM-SHA-512"  #PLAIN, SCRAM-SHA-256, SCRAM-SHA-512, OAUTHBEARER, GSSAPI
  kafka.broker.sasl.username: "usernamecreate"
  kafka.broker.sasl.password: "passwordcreate"
  kafka.indexer.logs.topics: "nameof the topic"
  kafka.indexer.group: "episilia-indexer-group"  # Kafka consumer-group for indexer
  

cpanel:
  cpanel.api.access.key: "token"
  cpanel.api.access.token: ""
  cpanel.api.grpc.port: "8080"
  cpanel.api.metrics.port: "8090"
  cpanel.gateway.server: "episilia_gateway:9002"
  kafka.group.cpanel: "episilia-cpanel-group"
  alert.prometheus.gateway: "pushgateway:5070"
  cpanel.ops.healthchecks.interval.mins: "5"
  cpanel.ops.healthchecks.exclude.list: ""

gateway:
  gateway.api.http.port: "9002"
  gateway.search.timeout.seconds: "120"
  gateway.search.url: "episilia_search:4040"

indexer:
  indexer.api.http.port: "9090"
  optimizer.api.http.port: "9080"
  indexer.schema.appid.fixed: "defaultApp"
  indexer.schema.appid.keys: ""
  indexer.schema.tenantid.fixed: "defaultTenant"
  indexer.schema.tenantid.keys: ""
  indexer.schema.exclude: "['time']"
  indexer.schema.message.key: "message"
  indexer.schema.timestamp.formats: "%Y-%m-%dT%H:%M:%S"
  indexer.schema.timestamp.key: "time"
  kafka.topic.index.live: "stagefiles"
  kafka.topic.index.optimized: "optfiles"
  kafka.topic.optimize.request: "stagefolder"

search:
  kafka.group.search: "episilia-search-group"
  search.api.grpc.port: "4040"
  search.api.response.max.mb: "100"
  search.api.timeout.seconds: "60"
  search.live.from.hours: "24"
  search.live.to.hours: "0"
  search.ops.index.cache.resetonstart: "true"

logwatcher:
  logwatcher.api.http.port: "9050"
  tail.api.http.port: "9005"
  alert.rules.file.url: "/bucket/folder/alert_rules.json"
  kafka.group.logwatcher: "episilia-logwatcher-group"
  kafka.group.logwatcher.alert: "episilia-logwatcher-alert-group"
  kafka.group.logwatcher.tail: "episilia-logwatcher-tail-group"
  kafka.topic.alert.response.out: "alert_out"
  kafka.topic.tail.request.in: "tail_in"
  kafka.topic.tail.response.out: "tail_out"
  indexer.ops.alert.enable: "true"
  indexer.ops.tail.enable: "true"
  indexer.live.block.maxwait.ms: "2000"
  indexer.live.block.maxrecord.count: "1000"

historic-search:
  gateway.api.http.port: "9001"
  search.api.grpc.port: "4041"
  search.api.response.max.mb: "100"
  search.api.timeout.seconds: "60"
  search.fixed.from.yyyymmddhh: "2022031200"
  search.fixed.to.yyyymmddhh: "2022031300"

resources:
  cpanel.cpu.limit: "500m"
  cpanel.cpu.request: "200m"
  indexer.cpu.limit: "700m"
  indexer.cpu.request: "400m"
  search.cpu.limit: "1"
  search.cpu.request: "500m"
  gateway.cpu.limit: "400m"
  gateway.cpu.request: "200m"
  optimizer.cpu.limit: "800m"
  optimizer.cpu.request: "500m"
  logwatcher.cpu.limit: "800m"
  logwatcher.cpu.request: "500m"
  tail.cpu.limit: "400m"
  tail.cpu.request: "200m"
  historic.search.cpu.limit: "800m"
  historic.search.cpu.request: "500m"
  cpanel.memory.limit: "500Mi"
  cpanel.memory.request: "200Mi"
  indexer.memory.limit: "700Mi"
  indexer.memory.request: "400Mi"
  search.memory.limit: "1500Mi"
  search.memory.request: "500Mi"
  gateway.memory.limit: "500Mi"
  gateway.memory.request: "200Mi"
  optimizer.memory.limit: "800Mi"
  optimizer.memory.request: "500Mi"
  logwatcher.memory.limit: "800Mi"
  logwatcher.memory.request: "500Mi"
  tail.memory.limit: "500Mi"
  tail.memory.request: "200Mi"
  historic.search.memory.limit: "1500Mi"
  historic.search.memory.request: "500Mi"

